### ISSUE TITLE
can't install jellyfinjac version 2020.01.30.1

### ISSUE THREAD

**Issue by chrome0313** [imaginary-upside/JellyfinJav#11]
can't install jellyfinjac version 2020.01.30.1
i can't install ver 2020.01.30.1 but possble to install previous version 0.4.2
fix this

**Comment by imaginary-upside** [comment]
It's a bit rude to just say "fix this". But anyway, send me a log or any other information which would let me fix this.

**Comment by ZeroSiks** [comment]
Having the same issue.. I get an infinite loading icon



Heres the log
> `[2021-02-06 15:55:00.337 +00:00] [ERR] Could not find handler for "/socket"
[2021-02-06 15:55:00.337 +00:00] [ERR] Error processing request: "Unable to find the specified file". URL: "http://ikande.ml:8096/socket?deviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84NC4wfDE2MTE4NDEzMzgwOTA1"
[2021-02-06 15:55:04.558 +00:00] [WRN] HTTP Response 200 to "45.77.33.88". Time (slow): 0:00:03.1497876. "http://ikande.ml:8096/Packages?PackageType=UserInstalled"
[2021-02-06 15:55:12.360 +00:00] [WRN] HTTP Response 200 to "45.77.33.88". Time (slow): 0:00:00.6086211. "http://ikande.ml:8096/Packages/JellyfinJav?AssemblyGuid=1d5fffc2-1028-4553-9660-bd4966899e44"
[2021-02-06 15:55:15.989 +00:00] [ERR] Error processing request. URL: "http://ikande.ml:8096/Packages/Installed/JellyfinJav?AssemblyGuid=1d5fffc2-1028-4553-9660-bd4966899e44&version=2020.01.30.1"
MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: JellyfinJav
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)`

**Comment by imaginary-upside** [comment]
Are you running Jellyfin 10.6? If so, then it should be because of this issue: https://github.com/jellyfin/jellyfin/issues/4688. I have 2020.01.30.1 configured to only target jellyfin 10.7, but it still shows up for older Jellyfin servers because of that issue.

**Comment by ZeroSiks** [comment]
I see.. yea that is probably why. Gonna wait till 10.7 gets a bit more fleshed out before upgrading tho. Thanks

**Comment by ZeroSiks** [comment]
I see.. yea that is probably why. Gonna wait till 10.7 gets a bit more fleshed out before upgrading tho. Thanks
