### ISSUE TITLE
No artwork is fetched

### ISSUE THREAD

**Issue by anhdowastaken** [imaginary-upside/JellyfinJav#15]
### Versions
- **Jellyfin**: 10.7.7
- **JellyfinJav**: 2021.4.4.0

### Enable javlibrary

- No artwork is fetched
- Error in log:
```
[18:14:00] [ERR] [48] MediaBrowser.Providers.Movies.MovieMetadataService: Error in Javlibrary
System.InvalidOperationException: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at JellyfinJav.Providers.JavlibraryProvider.JavlibraryImageProvider.GetImageResponse(String url, CancellationToken cancelToken)
   at MediaBrowser.Providers.Manager.ItemImageProvider.DownloadImage(BaseItem item, LibraryOptions libraryOptions, IRemoteImageProvider provider, RefreshResult result, IEnumerable`1 images, Int32 minWidth, ImageType type, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ItemImageProvider.RefreshFromProvider(BaseItem item, LibraryOptions libraryOptions, IRemoteImageProvider provider, ImageRefreshOptions refreshOptions, TypeOptions savedOptions, Int32 backdropLimit, Int32 screenshotLimit, ICollection`1 downloadedImages, RefreshResult result, CancellationToken cancellationToken)
```

### Disable javlibrary (R18 only)

- No artwork is fetched
- No error in log

**Comment by anhdowastaken** [comment]
Seem ok today so I temporarily close this issue. It might be network issue.
